server:
  port: 8080
spring:
  application:
    name: preference-center-user
  datasource:
    url: jdbc:postgresql://localhost:5432/preference_center
    username: tu_usuario
    password: tu_contraseña
  jpa:
    hibernate:
      ddl-auto: update  # O "create-drop" si estás en desarrollo
    show-sql: true
    properties:
      hibernate:
        format_sql: true
